/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.field.Display',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.Label',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.grid.column.Date',
        'Ext.form.field.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.plugin.CellEditing'
    ],

    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'menuPanel',
            resizable: true,
            style: '',
            width: 150,
            bodyStyle: 'background-color: #0066cc;',
            title: 'Menu',
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    itemId: 'menu',
                    bodyStyle: 'background-color: #d2d2cc; ',
                    items: [
                        {
                            xtype: 'menuitem',
                            itemId: 'home',
                            text: 'Home',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            id: 'o1',
                            itemId: 'o1',
                            text: 'Order ',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            id: 'o2',
                            itemId: 'o2',
                            text: 'Add Days / Detail',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            id: 'o3',
                            itemId: 'tran',
                            text: 'Transfer Order',
                            focusable: true
                        }
                    ],
                    listeners: {
                        click: 'onMenuClick'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'contentPanel',
            scrollable: true,
            layout: 'card',
            items: [
                {
                    xtype: 'panel',
                    hidden: true,
                    itemId: 'homePanel',
                    layout: 'border',
                    title: 'Home',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'south',
                            height: 300,
                            layout: 'column',
                            bodyPadding: 10,
                            collapsed: true,
                            collapseDirection: 'bottom',
                            collapsible: true,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    id: 'userid',
                                    readOnly: true
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    id: 'commonuser',
                                    readOnly: true
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    id: 'name',
                                    width: 420,
                                    readOnly: true
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    id: 'role',
                                    readOnly: true
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    id: 'vend',
                                    readOnly: true
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    id: 'sls',
                                    readOnly: true
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    id: 'sppgid',
                                    readOnly: true
                                },
                                {
                                    xtype: 'fieldset',
                                    width: '95%',
                                    layout: 'column',
                                    collapsed: true,
                                    collapsible: true,
                                    title: 'Security Options',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'spop1',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Application Access',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop2',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Add Days Detail Review',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop3',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Change Detail Hold',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop4',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Changed Detail Required Date',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop5',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Change Detail Ship Via',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop6',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Cancel Pick Ticket',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop7',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Re-print Pick Ticket',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop8',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Cancel Packing List',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop9',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Customer Adress Validation',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop10',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Drop Ship Address Validation',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            id: 'spop11',
                                            width: 30,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            id: 'spop12',
                                            width: 30,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            id: 'spop13',
                                            width: 30,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            id: 'spop14',
                                            width: 30,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'spop15',
                                            padding: 10,
                                            width: 140,
                                            fieldLabel: 'Transfer Order',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    id: 'email',
                                    width: 420,
                                    readOnly: true
                                },
                                {
                                    xtype: 'fieldset',
                                    collapsed: true,
                                    collapsible: true,
                                    title: 'Library List',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            id: 'libl',
                                            width: '90%',
                                            readOnly: true
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'fieldset',
                                    anchor: '80%',
                                    dock: 'top',
                                    title: 'User Data',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            id: 'udata',
                                            width: 950,
                                            readOnly: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            region: 'center',
                            layout: 'anchor',
                            bodyPadding: 10,
                            items: [
                                {
                                    xtype: 'numberfield',
                                    anchor: '30%',
                                    id: 'inOrd',
                                    fieldLabel: 'Enter Order Number',
                                    labelWidth: 150,
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'button',
                                    text: 'Submit',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'combobox',
                                    id: 'db',
                                    width: 407,
                                    fieldLabel: 'Database/Environment',
                                    labelWidth: 150,
                                    value: 'TS',
                                    store: 'storeEnv',
                                    valueField: 'id',
                                    listeners: {
                                        select: 'onDbSelect'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'My Panel'
                },
                {
                    xtype: 'panel',
                    id: 'panelO1',
                    itemId: 'o1Panel',
                    width: '100%',
                    layout: 'anchor',
                    title: 'Order Review/Maintenance',
                    items: [
                        {
                            xtype: 'panel',
                            height: 520,
                            resizable: true,
                            scrollable: true,
                            width: '90%',
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    draggable: true,
                                    height: 200,
                                    liquidLayout: true,
                                    liveDrag: true,
                                    margin: 5,
                                    width: '30%',
                                    collapsible: true,
                                    title: 'Customer',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'cust',
                                            width: '90%',
                                            fieldLabel: 'Bill to / Ship To',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            hidden: true,
                                            id: 'cust1',
                                            width: '90%',
                                            fieldLabel: 'Bill to / Ship To',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'cmcna1',
                                            width: '90%',
                                            fieldLabel: 'Name',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            id: 'adr',
                                            width: '90%',
                                            fieldLabel: 'Address',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'label',
                                            id: 'cvalmsg',
                                            style: 'color: red;',
                                            width: '90%'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            id: 'cval',
                                            width: '90%',
                                            text: 'Validate Address',
                                            listeners: {
                                                click: 'onCvalClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    draggable: true,
                                    height: 200,
                                    liveDrag: true,
                                    margin: 5,
                                    width: '30%',
                                    collapsible: true,
                                    title: 'Order',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oebdte',
                                            width: '90%',
                                            fieldLabel: 'Created Date',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oeslsm',
                                            width: '90%',
                                            fieldLabel: 'Sales Person',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oeudf2',
                                            width: '90%',
                                            fieldLabel: 'Job Name',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oeorrf',
                                            width: '90%',
                                            fieldLabel: 'Reference #',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    draggable: true,
                                    height: 200,
                                    liveDrag: true,
                                    margin: 5,
                                    width: '30%',
                                    collapsible: true,
                                    title: 'Header Dates',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oerqdt',
                                            width: '90%',
                                            fieldLabel: 'Required',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oedte2',
                                            width: '90%',
                                            fieldLabel: 'Must Ship',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'bd',
                                            width: '90%',
                                            fieldLabel: 'Base',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'pd',
                                            width: '90%',
                                            fieldLabel: 'Projected',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    anchor: '90%',
                                    draggable: true,
                                    height: 250,
                                    liveDrag: true,
                                    margin: 5,
                                    width: '30%',
                                    collapsible: true,
                                    title: 'Shipping',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oesvsv',
                                            width: '90%',
                                            fieldLabel: 'Ship Via',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oesvds',
                                            width: '90%',
                                            fieldLabel: 'Description',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            id: 'ds',
                                            width: '90%',
                                            fieldLabel: 'Drop Ship #',
                                            readOnly: true,
                                            hideTrigger: true
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 85,
                                            id: 'dsadr',
                                            width: '90%',
                                            fieldLabel: 'Name/Address',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'label',
                                            anchor: '90%',
                                            id: 'dsvalm',
                                            style: 'color: blue;',
                                            width: '90%'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            id: 'dsval',
                                            width: '90%',
                                            text: 'MyButton',
                                            listeners: {
                                                click: 'onDsvalClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    draggable: true,
                                    height: 250,
                                    liveDrag: true,
                                    margin: 5,
                                    width: '30%',
                                    collapsible: true,
                                    title: 'Holds / Flags',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'hold',
                                            width: '90%',
                                            fieldLabel: 'Hold Code',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oectrm',
                                            width: '90%',
                                            fieldLabel: 'Order Terms Code',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'crfgl',
                                            width: '90%',
                                            fieldLabel: 'Credit Hold Fag',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    draggable: true,
                                    height: 250,
                                    liveDrag: true,
                                    margin: 5,
                                    width: '30%',
                                    collapsible: true,
                                    title: 'Contact Data',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'oecont',
                                            width: '90%',
                                            fieldLabel: 'Number',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            height: 100,
                                            scrollable: true,
                                            width: '100%',
                                            columnLines: true,
                                            hideHeaders: true,
                                            store: 'storeFRC',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    hidden: true,
                                                    dataIndex: 'EFCUST',
                                                    text: 'Customer'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    hidden: true,
                                                    dataIndex: 'EFCONT',
                                                    text: 'Contact'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    hidden: true,
                                                    dataIndex: 'EFSEQ',
                                                    text: 'Seq'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 50,
                                                    dataIndex: 'EFDOCT',
                                                    text: 'doc'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    hidden: true,
                                                    width: 175,
                                                    dataIndex: 'EFRNAM',
                                                    text: 'Ref'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: '90%',
                                                    cellWrap: true,
                                                    dataIndex: 'EFEMAL',
                                                    text: 'Email'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            height: 500,
                            resizable: true,
                            scrollable: true,
                            width: 1526,
                            title: 'Detail by Warehouse',
                            columnLines: true,
                            store: 'storeMWVD',
                            viewConfig: {
                                height: '50%'
                            },
                            columns: [
                                {
                                    xtype: 'actioncolumn',
                                    width: 176,
                                    items: [
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                secopt = Ext.getCmp('spop6').getValue();

                                                hold = r.data.HOLD;
                                                console.log('secopt6: ', secopt, hold);
                                                if (secopt !== 'Y' || hold == 'Y'){
                                                    return '';
                                                } else {
                                                    console.log('Turn#: ', r.data.TURN);
                                                    if (r.data.TURN >0){  //read your condition from the record
                                                        return 'icon-PICDEL';    // add a CSS-Class to display what icon you like
                                                    } else {
                                                        return '';        //add no CSS-Class
                                                    }
                                                }
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                storeD = Ext.getStore('storeMWVD');
                                                db = Ext.getCmp('db').getValue();
                                                ord = Ext.getCmp('inOrd').getValue();



                                                storeD.load({
                                                    params: {
                                                        DB: db,
                                                        PGID: 'MW',
                                                        ORD: ord,
                                                        Action: 'DIP',
                                                        Turn: record.data.TURN

                                                    },
                                                    callback: function(){
                                                        location.hash = 'o1';
                                                    }
                                                });
                                            },
                                            tooltip: 'Remove Pick Ticket '
                                        },
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                secopt = Ext.getCmp('spop8').getValue();
                                                hold = r.data.HOLD;
                                                console.log('secopt8: ', secopt, hold);
                                                if (secopt !== 'Y' || hold == 'Y'){
                                                    return '';
                                                } else {
                                                    //if (r.data.TURN === 0){  //read your condition from the record
                                                    return 'icon-PIC';    // add a CSS-Class to display what icon you like
                                                    //   } else {
                                                    //       return '';        //add no CSS-Class
                                                    //   }
                                                }
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                storeD = Ext.getStore('storeMWVD');
                                                db = Ext.getCmp('db').getValue();
                                                ord = Ext.getCmp('inOrd').getValue();

                                                if (record.data.TURN > 0){
                                                    action = 'RPPACK';
                                                } else {
                                                    action = 'PPACK';
                                                }


                                                storeD.load({
                                                    params: {
                                                        DB: db,
                                                        PGID: 'MW',
                                                        ORD: ord,
                                                        Action: action,
                                                        Turn: record.data.TURN

                                                    },
                                                    callback: function(){
                                                        location.hash = 'o1';
                                                    }
                                                });
                                            },
                                            tooltip: ' Print / Re-print - Pick Tick'
                                        },
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                secopt = Ext.getCmp('spop11').getValue();
                                                hold = r.data.HOLD;
                                                console.log('secoptcrtpac: ', secopt, hold);
                                                if (secopt !== 'Y' || hold == 'Y'){
                                                    return '';
                                                } else {
                                                    if (r.data.PKL === 0){  //read your condition from the record
                                                        return 'icon-PACNEW';    // add a CSS-Class to display what icon you like
                                                    } else {
                                                        return '';        //add no CSS-Class
                                                    }
                                                }
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                storeD = Ext.getStore('storeMWVD');
                                                db = Ext.getCmp('db').getValue();
                                                ord = Ext.getCmp('inOrd').getValue();

                                                action = 'CRTPKL';


                                                storeD.load({
                                                    params: {
                                                        DB: db,
                                                        PGID: 'MW',
                                                        ORD: ord,
                                                        Action: action,
                                                        PKL: record.data.PKL

                                                    },
                                                    callback: function(){
                                                        location.hash = 'o1';
                                                    }
                                                });
                                            },
                                            tooltip: 'Create Packing list'
                                        },
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                secopt = Ext.getCmp('spop12').getValue();
                                                hold = r.data.HOLD;
                                                console.log('secoptprtpac: ', secopt, hold);
                                                if (secopt !== 'Y' || hold == 'Y'){
                                                    return '';
                                                } else {
                                                    if (r.data.PKL !== 0){  //read your condition from the record
                                                        return 'icon-PAC';    // add a CSS-Class to display what icon you like
                                                    } else {
                                                        return '';        //add no CSS-Class
                                                    }
                                                }
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                storeD = Ext.getStore('storeMWVD');
                                                db = Ext.getCmp('db').getValue();
                                                pkl = record.data.PKL;

                                                action = 'PRTPKL';


                                                storeD.load({
                                                    params: {
                                                        DB: db,
                                                        PGID: 'MW',
                                                        PKL: pkl,
                                                        Action: action,
                                                        Turn: record.data.TURN

                                                    },
                                                    callback: function(){
                                                        location.hash = 'o1';
                                                    }
                                                });
                                            },
                                            tooltip: 'Print the  Packing list'
                                        },
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                secopt = Ext.getCmp('spop7').getValue();
                                                hold = r.data.HOLD;
                                                console.log('secopt7: ', secopt, hold);
                                                if (secopt !== 'Y' || hold == 'Y'){
                                                    return '';
                                                } else {
                                                    if (r.data.PKL >0){  //read your condition from the record
                                                        return 'icon-PACDEL';    // add a CSS-Class to display what icon you like
                                                    } else {
                                                        return '';        //add no CSS-Class
                                                    }
                                                }
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                storeD = Ext.getStore('storeMWVD');
                                                db = Ext.getCmp('db').getValue();
                                                ord = Ext.getCmp('inOrd').getValue();



                                                storeD.load({
                                                    params: {
                                                        DB: db,
                                                        PGID: 'MW',
                                                        ORD: ord,
                                                        Action: 'DPK',
                                                        PKL: record.data.PKL

                                                    },
                                                    callback: function(){
                                                        location.hash = 'o1';
                                                    }
                                                });
                                            },
                                            tooltip: 'Remove packing slip'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'ODORD',
                                    text: 'Order'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'ODORST',
                                    text: 'Line Stat'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 61,
                                    dataIndex: 'ODWH',
                                    text: 'Whs'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 171,
                                    cellWrap: true,
                                    dataIndex: 'STAT',
                                    text: 'Status'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 78,
                                    dataIndex: 'DHOLD',
                                    text: 'Hold',
                                    editor: {
                                        xtype: 'combobox',
                                        id: 'holdcode',
                                        store: 'storeDhold',
                                        valueField: 'text'
                                    }
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'BD',
                                    text: 'Base<br>Date',
                                    format: 'm/d/Y'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'PD',
                                    text: 'Projected <br> Date',
                                    format: 'm/d/Y'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'MS',
                                    text: 'Must <br> Ship'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.data.MS !== record.data.ODRQDT){
                                            metaData.style = 'Background-color: coral;';
                                        }
                                        return value;
                                    },
                                    dataIndex: 'ODRQDT',
                                    text: 'Required<br>Date',
                                    editor: {
                                        xtype: 'datefield',
                                        id: 'rqdate',
                                        submitFormat: 'Y-m-d'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        val = '(' + value + ') ' + record.data.ODSVDS;
                                        return val;
                                    },
                                    width: 203,
                                    dataIndex: 'ODSVSV',
                                    text: 'Shp<br>Via',
                                    editor: {
                                        xtype: 'combobox',
                                        hidden: true,
                                        id: 'svia',
                                        width: 200,
                                        store: 'storeSvia',
                                        valueField: 'id'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'DATSHP',
                                    text: 'Shipped'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 63,
                                    dataIndex: 'LS',
                                    text: 'Tops <br> Scan'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.data.PTE){
                                            val = "<a href='" +  record.data.PTLINK + "' target = 'PKL'>" + value + "</a>";
                                        } else {
                                            val = value;
                                        }
                                        return val;
                                    },
                                    dataIndex: 'TURN',
                                    text: 'Turn #'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.data.PLE){
                                            val = "<a href='" +  record.data.PLLINK + "' target = 'PKL'>" + value + "</a>";
                                        } else {
                                            val = value;
                                        }
                                        return val;
                                    },
                                    dataIndex: 'PKL',
                                    text: 'Packing<br>List'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.data.PTE){
                                            val = "<a href='" +  value + "' target = 'PKL'>viewPick</a>";
                                        } else {
                                            val = '';
                                        }
                                        return val;
                                    },
                                    hidden: true,
                                    dataIndex: 'PTLINK'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    hidden: true,
                                    dataIndex: 'PTE'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.data.PLE){
                                            val = "<a href='" +  value + "' target = 'PKL'>viewPack</a>";
                                        } else {
                                            val = '';
                                        }
                                        return val;
                                    },
                                    hidden: true,
                                    dataIndex: 'PLLINK'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    hidden: true,
                                    dataIndex: 'PLE'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'HOLD'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    align: 'center',
                                    dataIndex: 'PKLP',
                                    text: 'Packing List<br>Printed'
                                }
                            ],
                            plugins: [
                                {
                                    ptype: 'cellediting',
                                    listeners: {
                                        beforeedit: 'onCellEditingBeforeEdit'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    hidden: true,
                    id: 'panelO2',
                    itemId: 'o2Panel',
                    layout: 'fit',
                    title: 'Option 2 Panel'
                },
                {
                    xtype: 'panel',
                    id: 'tran',
                    itemId: 'tranPanel',
                    title: 'My Panel'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onMainViewAfterRender'
    },

    onMenuClick: function(menu, item, e, eOpts) {
        location.hash = item.itemId;
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.getStore('storeFRC').load();
        store = Ext.getStore('storeH');
        storeD = Ext.getStore('storeMWVD');
        db = Ext.getCmp('db').getValue();
        ord = Ext.getCmp('inOrd').getValue();

        store.load({
            params: {
                DB: db,
                PGID: 'MW',
                ORD: ord
            }
        });

        storeD.load({
            params: {
                DB: db,
                PGID: 'MW',
                ORD: ord
            },
            callback:function(records, operation, success){
                if(records.length === 0){
                    Ext.Msg.alert('Order Number Check', 'Order number ' + ord + ' was not found in the ' + db + ' Database');
                }   else {
                    location.hash = 'o1';
                }
            }
        });

    },

    onDbSelect: function(combo, record, eOpts) {
        store = Ext.getStore('storeSec');
        db = Ext.getCmp('db').getValue();
        store.load({
            params: {
                DB: db,
                PGID: 'MW'
            }
        });
    },

    onCvalClick: function(button, e, eOpts) {

                cust = Ext.getCmp('cust1').getValue();
                window.open( 'http://ERPDC:85/PHP/Gemini/Customer/ValidateAdr.php?DB=TS&cust=' + cust  ,'Address Validation','width=1000,height=800');

    },

    onDsvalClick: function(button, e, eOpts) {
        cust = Ext.getCmp('cust1').getValue();
        dsnmbr = Ext.getCmp('ds').getValue();
        window.open( 'http://ERPDC:85/PHP/Gemini/Customer/ValidateDsAdr.php?DB=TS&cust=' + cust + '&DS='+dsnmbr ,'Drop Ship Validation','width=1000,height=800');
    },

    onCellEditingBeforeEdit: function(editor, context, eOpts) {
        if (context.field == 'DHOLD'){
               if (Ext.getCmp('spop3').getValue() !== 'Y'){
                   Ext.Msg.alert('Security Error', 'You are not authorized to modify the Hold Code.');
                   return false;
               }
        }
        if (context.field == 'ODRQDT'){
               if (Ext.getCmp('spop4').getValue() !== 'Y'){
                   Ext.Msg.alert('Security Error', 'You are not authorized to modify the Required Date');
               }
        }

        if (context.field == 'ODSVSV'){
               if (Ext.getCmp('spop5').getValue() !== 'Y'){
                   Ext.Msg.alert('Security Error', 'You are not authorized to modify the Ship Via Code.');
                   return false;
               }
        }



    },

    onMainViewAfterRender: function(component, eOpts) {
        // separating the GET parameters from the current URL
        var getParams = document.URL.split("?");
        // transforming the GET parameters into a dictionnary
        var params = Ext.urlDecode(getParams[getParams.length - 1]);

        if ((typeof params.DB) != "undefined"){
            db = Ext.getCmp('db').setValue(params.DB);
        }

        store = Ext.getStore('storeSec');
        db = Ext.getCmp('db').getValue();
        store.load({
            params: {
                DB: db,
                PGID: 'MW'
            }
        });

        if ((typeof params.ORD) != "undefined"){

            store = Ext.getStore('storeH');
            storeD = Ext.getStore('storeMWVD');
            db = Ext.getCmp('db').getValue();
            ord1 = params.ORD.split("#");
            console.log('order: ', ord1);
            ord = ord1[0];
            Ext.getCmp('inOrd').setValue(ord1[0]);

            store.load({
                params: {
                    DB: db,
                    PGID: 'MW',
                    ORD: ord
                }
            });

            storeD.load({
                params: {
                    DB: db,
                    PGID: 'MW',
                    ORD: ord
                },
                callback: function(){
                    location.hash = 'o1';
                }
            });
             Ext.getStore('storeFRC').load();
        }



        Ext.getStore('storeSvia').load();
        Ext.getStore('storeDhold').load();

        if (Ext.get('loader')) {
            Ext.get('loader').remove();
        }



    }

});