/*
 * File: app/store/storeDhold.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeDhold', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeDhold',
            autoLoad: false,
            autoSync: true,
            proxy: {
                type: 'jsonp',
                url: 'http://erpdc:10080/Gemini/Order/GetSYUDFV.php',
                reader: {
                    type: 'json',
                    rootProperty: 'root'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'text'
                }
            ],
            listeners: {
                beforeload: {
                    fn: me.onJsonpstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonpstoreBeforeLoad: function(store, operation, eOpts) {

                db = Ext.getCmp('db').getValue();


              store.getProxy().extraParams = {
                        DB: db,
                        PGID: 'MW',
                  TABLE: 'OEOUDT',
                  FIELD: 'DHOLD'
        };
    }

});