/*
 * File: app/model/modelMWV.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelMWV', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'OEORD'
        },
        {
            name: 'CUST'
        },
        {
            name: 'CMCNA1'
        },
        {
            name: 'HOLD'
        },
        {
            name: 'OEBDTE'
        },
        {
            name: 'OERQDT'
        },
        {
            name: 'OEDTE2'
        },
        {
            name: 'OEUDF2'
        },
        {
            name: 'OEORRF'
        },
        {
            name: 'OECTRM'
        },
        {
            name: 'OESLSM'
        },
        {
            name: 'OECONT'
        },
        {
            name: 'OESVSV'
        },
        {
            name: 'OESVDS'
        },
        {
            name: 'ADR'
        },
        {
            name: 'CRFGL'
        },
        {
            name: 'OEDTE3'
        },
        {
            name: 'OEDTE4'
        },
        {
            name: 'RPTCLS'
        },
        {
            name: 'RPTWHS'
        },
        {
            name: 'OPTADDS'
        },
        {
            name: 'PCADDS'
        },
        {
            name: 'DOLADDS'
        },
        {
            name: 'WHSADDS'
        },
        {
            name: 'PD'
        },
        {
            name: 'BD'
        },
        {
            name: 'TITLE'
        },
        {
            name: 'DSHP'
        },
        {
            name: 'DSHPADR'
        },
        {
            name: 'DVAL'
        },
        {
            name: 'DVALM'
        }
    ]
});