/*
 * File: app/store/storeMWVD.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeMWVD', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelMWVD',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeMWVD',
            autoSync: true,
            model: 'MyApp.model.modelMWVD',
            data: [
                {
                    ODORD: 'autem',
                    BD: '6/13/2003',
                    PD: '10/6/2008',
                    MS: 'dolorum',
                    LS: 'fugit',
                    ODWH: 922,
                    XXX: 'alias',
                    DATSHP: '2/20/2008',
                    DHOLD: 'distinctio',
                    ODORST: 'voluptas',
                    ODSHPS: 'dicta',
                    ODSVSV: 'ut',
                    TURN: 883,
                    PKL: 202,
                    STAT: 'voluptatibus',
                    ODSVDS: 'nihil',
                    ODRQDT: 'provident'
                },
                {
                    ODORD: 'asperiores',
                    BD: '11/5/2001',
                    PD: '1/3/2002',
                    MS: 'ut',
                    LS: 'qui',
                    ODWH: 752,
                    XXX: 'aspernatur',
                    DATSHP: '8/7/2010',
                    DHOLD: 'temporibus',
                    ODORST: 'et',
                    ODSHPS: 'magni',
                    ODSVSV: 'amet',
                    TURN: 425,
                    PKL: 227,
                    STAT: 'earum',
                    ODSVDS: 'voluptatem',
                    ODRQDT: 'libero'
                },
                {
                    ODORD: 'dolorem',
                    BD: '4/17/2001',
                    PD: '12/25/2007',
                    MS: 'ducimus',
                    LS: 'ut',
                    ODWH: 357,
                    XXX: 'dicta',
                    DATSHP: '6/15/2010',
                    DHOLD: 'exercitationem',
                    ODORST: 'ex',
                    ODSHPS: 'assumenda',
                    ODSVSV: 'error',
                    TURN: 60,
                    PKL: 783,
                    STAT: 'incidunt',
                    ODSVDS: 'consequatur',
                    ODRQDT: 'necessitatibus'
                }
            ],
            proxy: {
                type: 'jsonp',
                url: 'http://erpdc:10080/Gemini/Order/GetVMWD.php',
                reader: {
                    type: 'json',
                    rootProperty: 'root'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onJsonpstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonpstoreBeforeLoad: function(store, operation, eOpts) {

                db = Ext.getCmp('db').getValue();
                ord = Ext.getCmp('inOrd').getValue();

              store.getProxy().extraParams = {
                        DB: db,
                        PGID: 'MW',
                  ORD: ord
        };


    }

});