/*
 * File: app/model/modelSec.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelSec', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'SPUSER'
        },
        {
            name: 'SPPGID'
        },
        {
            name: 'SPOP01'
        },
        {
            name: 'SPOP02'
        },
        {
            name: 'SPOP03'
        },
        {
            name: 'SPOP04'
        },
        {
            name: 'SPOP05'
        },
        {
            name: 'SPOP06'
        },
        {
            name: 'SPOP07'
        },
        {
            name: 'SPOP08'
        },
        {
            name: 'SPOP09'
        },
        {
            name: 'SPOP10'
        },
        {
            name: 'SPOP11'
        },
        {
            name: 'SPOP12'
        },
        {
            name: 'SPOP13'
        },
        {
            name: 'SPOP14'
        },
        {
            name: 'SPOP15'
        },
        {
            name: 'ROLE'
        },
        {
            name: 'NAME'
        },
        {
            name: 'VEND'
        },
        {
            name: 'SLS'
        },
        {
            name: 'EMAIL'
        },
        {
            name: 'COMMONUSER'
        },
        {
            name: 'USER'
        },
        {
            name: 'libl'
        },
        {
            name: 'MSG'
        },
        {
            name: 'UDATA'
        }
    ]
});