/*
 * File: app/model/modelMWVD.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelMWVD', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Date',
        'Ext.data.field.String',
        'Ext.data.field.Integer',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            name: 'ODORD'
        },
        {
            type: 'date',
            name: 'BD'
        },
        {
            type: 'date',
            name: 'PD'
        },
        {
            type: 'string',
            name: 'MS'
        },
        {
            name: 'LS'
        },
        {
            type: 'int',
            name: 'ODWH'
        },
        {
            name: 'XXX'
        },
        {
            type: 'date',
            name: 'DATSHP'
        },
        {
            name: 'DHOLD'
        },
        {
            name: 'ODORST'
        },
        {
            name: 'ODSHPS'
        },
        {
            name: 'ODSVSV'
        },
        {
            type: 'int',
            name: 'TURN'
        },
        {
            type: 'int',
            name: 'PKL'
        },
        {
            name: 'STAT'
        },
        {
            name: 'ODSVDS'
        },
        {
            type: 'string',
            name: 'ODRQDT'
        },
        {
            name: 'PKLP'
        },
        {
            name: 'PLLINK'
        },
        {
            name: 'PTLINK'
        },
        {
            type: 'boolean',
            name: 'PLE'
        },
        {
            type: 'boolean',
            name: 'PTE'
        },
        {
            name: 'HOLD'
        }
    ]
});